#!/bin/sh
#
# Graph test: regression test for "  " instead of "──"

. libtest.sh

test_graph <<EOF
commit A2 A1 R
    Commit A2 - merge A1 and R
commit B A1 R
    Commit B - merge A1 and R
commit C A1 R
    Commit C - merge A1 and R
commit A1 R
    Commit A1 - after R
commit D2 R D1
    Commit D2 - merge R and D1
commit D1 R
    Commit D1 - after R
commit R
    Commit R
EOF

assert_equals stdout <<EOF
●─╮ Commit A2 - merge A1 and R
│ │ ●─╮ Commit B - merge A1 and R
│ │ │ │ ●─╮ Commit C - merge A1 and R
●─│─┴─│─╯ │ Commit A1 - after R
│ │ ╭─╯ ╭─╯ ●─╮ Commit D2 - merge R and D1
│ │ │ ╭─╯ ╭─╯ ● Commit D1 - after R
◎─┴─┴─┴───┴───╯ Commit R
EOF
