#!/bin/sh
#
# Graph test: regression test for "─┬" instead of "──"

. libtest.sh

test_graph <<EOF
commit A2 A1 S
    Commit A2 - merge A1 and S
commit B A1 S
    Commit B - merge A1 and S
commit C A1 S
    Commit C - merge A1 and S
commit A1 S
    Commit A1 - after S
commit D2 S D1
    Commit D2 - merge S and D1
commit D1 S
    Commit D1 - after S
commit E S R
    Commit E - merge S and R
commit S R
    Commit S - after R
commit R
    Commit R
EOF

assert_equals stdout <<EOF
●─╮ Commit A2 - merge A1 and S
│ │ ●─╮ Commit B - merge A1 and S
│ │ │ │ ●─╮ Commit C - merge A1 and S
●─│─┴─│─╯ │ Commit A1 - after S
│ │ ╭─╯ ╭─╯ ●─╮ Commit D2 - merge S and D1
│ │ │ ╭─╯ ╭─╯ ● Commit D1 - after S
│ │ │ │ ╭─╯ ╭─╯ ●─╮ Commit E - merge S and R
●─┴─┴─┴─┴───┴───╯ │ Commit S - after R
◎─────────────────╯ Commit R
EOF
